fix: pass release image tag to main deployments

diff --git a/.github/actions/deploy_branch/action.yml b/.github/actions/deploy_branch/action.yml
--- a/.github/actions/deploy_branch/action.yml
+++ b/.github/actions/deploy_branch/action.yml
@@ -89,6 +89,11 @@ runs:
         LAA_IPS: ${{ steps.get_laa_ips.outputs.laa-ips }}
         APP_ENVIRONMENT: ${{ inputs.app-environment }}
       run: |
+        if [ -z "${IMAGE_TAG}" ]; then
+          echo "image-tag input is required."
+          exit 1
+        fi
+
         ingress_name="$RELEASE_NAME-data-access-api"
         external_host="$RELEASE_NAME-$KUBE_NAMESPACE.cloud-platform.service.justice.gov.uk"
         internal_host="$RELEASE_NAME-internal-$KUBE_NAMESPACE.internal-non-prod.cloud-platform.service.justice.gov.uk"
@@ -96,7 +101,7 @@ runs:
         internal_identifier="$RELEASE_NAME-data-access-api-internal-$KUBE_NAMESPACE-green"
         branch_name="$BRANCH_NAME"
 
-        echo "Deploying commit: $GIT_SHA under release name: $RELEASE_NAME to $external_host and $internal_host..."
+        echo "Deploying image tag: $IMAGE_TAG under release name: $RELEASE_NAME to $external_host and $internal_host..."
 
         echo "branch name: $branch_name"
 
